### PR TITLE
Add instructions to use with fish shell

### PR DESCRIPTION
**Pull request by antoine-gallix**
There is a file that can be sourced in fish shell to get environment activation/deactivation functionality. This changes documents how to use this file. See : ``https://github.com/conda/conda/blob/master/shell/etc/fish/conf.d/conda.fish``

### CODE REVIEW

**Comment by electronwill** [comment]
Thank you very much @antoine-gallix ! cc'ing @msarahan and @kalefranz in case any other changes need to be made in the docs around this, such as adding references to the fish shell in other places, or adding any necessary warnings about limitations of conda support for the fish shell.

**Comment by electronwill** [comment]
If there are no further comments or changes I'll merge this later today.

**Comment by antoine-gallix** [comment]
@electronwill , you know what? This my first contribution ever to an open source project! I'm proud of myself! Haha!

**Comment by msarahan** [comment]
@antoine-gallix thanks - keep up the great work.

**Pull request merged**
