### PR TITLE
Add test drive redirect

### PR DESCRIPTION
**Pull request by electronwill**
Add redirect from using/test-drive.html to test-drive.html, since
the cheat sheets use that link.

### CODE REVIEW

**Comment by electronwill** [comment]
@kerrywatson1 @asmeurer @ilanschnell Ready to merge.

**Comment by electronwill** [comment]
More precisely, the cheat sheets use bit.ly/tryconda , which goes to http://conda.pydata.org/docs/using/test-drive.html , which is currently a 404 but should redirect to http://conda.pydata.org/docs/test-drive.html .

**Comment by kerrywatson1** [comment]
A sad temporary work-around is to put pages in both places. Ie if we dont
have access to redirects.

K.

**Comment by electronwill** [comment]
As soon as this merge request goes through, we should have the redirect up and working.

**Pull request merged**
