### PR TITLE
Add documentation for the license_file build option in meta.yaml.

### PR DESCRIPTION
**Pull request by jasongrout**
See https://github.com/conda/conda-build/pull/545

### CODE REVIEW

**Comment by ilanschnell** [comment]
Thanks for writing this up, Jason.  Can you could change it to the `about` section?  Thanks

**Comment by jasongrout** [comment]
I changed and rebased the commit to refer to the about/license_file option.

**Comment by ilanschnell** [comment]
I merged the PR.  Once we release the next version of conda-build, we can merge this documentation as well.

**Comment by jasongrout** [comment]
Thanks.  I'm really looking forward to the next release of conda-build, as it also fixes 2 annoying things about building on windows.  I hope it's soon.

**Pull request merged**
