### PR TITLE
update conda docs for MRO

### PR DESCRIPTION
**Pull request by kalefranz**
This is a first draft.  DO NOT MERGE YET.  Some of the specifics (like package names) are subject to change.

### CODE REVIEW

**Comment by electronwill** [comment]
@kalefranz (and @csoja and @kerrywatson1 ), currently docs on using R and MRO are split between the conda docs and Anaconda docs:
https://conda.io/docs/user-guide/tasks/use-r-with-conda.html
https://conda.io/docs/user-guide/tasks/use-mro-with-conda.html
https://docs.anaconda.com/anaconda/user-guide/tasks/use-r-language

(There are also a couple of related tutorials in the Navigator docs:
https://docs.anaconda.com/anaconda/navigator/tutorials/create-r-environment
https://docs.anaconda.com/anaconda/navigator/tutorials/r-lang )

It would be good to centralize these in one place, and just link to them from the other place.

I think that this has less to do with conda itself and more to do with the packages in Anaconda, so it would be best to centralize the R/MRO docs at https://docs.anaconda.com/anaconda/user-guide/tasks/use-r-language .

https://conda.io/docs/user-guide/tasks/use-r-with-conda.html and https://conda.io/docs/user-guide/tasks/use-mro-with-conda.html can become redirects to that page in the Anaconda docs, or at least brief blubs with links to that page in the Anaconda docs.

Does this sound good to you, @kalefranz ?

**Comment by kerrywatson1** [comment]
Crystal also mentioned that she'd like them to be consolidated, preferably on Anaconda docs, so maybe you could touch base with her if you haven't already.

**Comment by kalefranz** [comment]
Sounds good to me

**Comment by electronwill** [comment]
Redirects are added in https://github.com/conda/conda-docs/pull/555 and content is moved to Distribution docs in https://github.com/ContinuumIO/distribution-docs/pull/453 .

**Pull request closed without merging**
