### PR TITLE
DOC : documentation updates to go with git_rev

### PR DESCRIPTION
**Pull request by tacaswell**
See https://github.com/conda/conda-build/pull/214

### CODE REVIEW

**Comment by asmeurer** [comment]
@kerrywatson1 @electronwill can we backport these changes to the current docs?

**Comment by electronwill** [comment]
Looks like there are three changes here.

1) Changing git_tag to git_rev everywhere, with a comment in that one place noting that it can be any string that git knows how to checkout. Sounds good to me.

2) Adding GIT_FULL_HASH to that table. Also good with me.

3) Adding 'git_rev: {{ environ('GIT_FULL_HASH') }}' after 'git_url: ../'. This seems to have spawned some discussion, and it looks like you guys decided not to make that change, but I want to make sure.

I'm glad to backport 1 & 2 and omit 3, or whatever else you think is best.

**Comment by electronwill** [comment]
Oops, should have tagged you @asmeurer

**Comment by asmeurer** [comment]
Yes, I think your assessment is correct.

**Comment by electronwill** [comment]
@asmeurer now backported as https://github.com/conda/conda-docs/pull/137

**Comment by tacaswell** [comment]
Sorry for dropping the ball on this, completely fell off my radar.

**Pull request closed without merging**
