### PR TITLE
Fix capitalization of Note: to NOTE:

### PR DESCRIPTION
**Pull request by electronwill**
Change Note: to NOTE: 7 times.

### CODE REVIEW

**Comment by asmeurer** [comment]
Shouldn't we just be using the `note` Sphinx directive?

**Comment by asmeurer** [comment]
(also this can't be merged)

**Comment by asmeurer** [comment]
I think this is the only pull request left by you guys. I didn't merge it because there are merge conflicts.

**Comment by electronwill** [comment]
Great! I'll kill this PR and make one new one to replace it.

**Pull request closed without merging**
