### PR TITLE
possible fix for scrape_help

### PR DESCRIPTION
**Pull request by electronwill**
possible fix for scrape_help

### CODE REVIEW

**Comment by electronwill** [comment]
@msarahan , it appears that conda-docs builds are broken because this script expects the output of 'conda --help' to have a line containing just whitespace and 'other commands:', which it doesn't, possibly because the help text was changed in a recent version of conda. Adding this if statement does seem to prevent the error, but I'd like your help figuring out what the script is trying to build a list of-- I'm not sure what is meant by 'external commands' or 'other commands'. Really making the script compatible with the current version of conda may require more than just this if statement.

**Comment by msarahan** [comment]
Ah, I see.  Conda's CLI was implemented to be extensible, where people could register add-ons, like conda-build or conda-build-all, and these would become part of what conda -h showed.

I think @kalefranz may have done away with that for performance reasons.  That argparse bit was adding like 1-2 *seconds* to each conda command.  If this fix works, I'm +1 on it.

**Comment by electronwill** [comment]
Thank you!

@kalefranz , sorry to bother you, but could you please take a look at this and help me understand what scrape_help.py does?

It looks like it was scraping the command line help text for conda build and conda env as well as conda, but the help text has changed and this is no longer working.

Maybe it generates http://conda.pydata.org/docs/commands.html ?

This PR removes the conda build and conda env code that wasn't working and leaves the conda code that was, and I think it will run without errors.

However if this was building an important part of the docs then I need to replace that code instead of just removing it.

I think since this script was written you've done some work with JSON help output and accessing conda commands through an API, so it may be possible to replace the whole script with a single line once we figure out what it's doing.

**Comment by electronwill** [comment]
Replaced by https://github.com/conda/conda-docs/pull/401 .

**Pull request closed without merging**
