### PR TITLE
prerequisite note added about python

### PR DESCRIPTION
**Pull request by shrutibhutaiya**

### CODE REVIEW

**Comment by mingwandroid** [comment]
This is true for all OSes, but I don't think saying this is really necessary, we are still a somewhat Python oriented data science platform and I believe most people would have no expectation that we do not provide Python itself!

**Comment by mingwandroid** [comment]
Thank you for the suggestion and the PR, the docs team may agree that it is bestg to make this clear to people, so you may want to consider moving this warning to a more globally relevant position? I'd also suggest a slight gramattical and clarification improvement of:

> one does not have to install it explicitly (either via conda or any other way).

Cheers!

**Comment by shrutibhutaiya** [comment]
Cheers !

**Comment by rrigdon** [comment]
I don't feel this needs to be pointed out specifically.

**Pull request closed without merging**
