### PR TITLE
Use doctr to deploy the documentation

### PR DESCRIPTION
**Pull request by asmeurer**
So here's the deal:

- I still have push access to this repository (admin access, by the looks of it).
- I don't actually want it, believe it or not. If I want to suggest a change, I'm happy to make a pull request from my fork and have a conda developer merge it.
- The [automatic deployment in this repo](https://github.com/conda/conda-docs/blame/9710f069c7dc7cdf35792cd1db04cbc6e769b984/.travis.yml#L7) is done via an encrypted personal access token on my account. In other words, if you remove my push access, the automatic deployment will break.
- I don't want to have a personal access token on my account. These are somewhat insecure, as it turns out, as they grant full read and write access to all my public repos. If it leaked (it's avaiable as an encrypted environment variable in every Travis build on this repo), it would be equivalent to leaking my GitHub password. 
- I (along with Gil Forsyth) have been working on a tool called [Doctr](https://drdoctr.github.io/doctr/), which makes it easy to deploy documentation to GitHub pages from Travis CI. Basically, I've taken the scripts that were in this repo and wrapped them nicely in a simple command. 

We are already using Doctr for SymPy to deploy dev docs to http://docs.sympy.org/dev/ (we also use it for doctr itself to deploy to https://drdoctr.github.io/doctr/). 

One nice thing about doctr is that instead of using a personal access token, it uses deploy keys. This is basically a special ssh key, which is encrypted in Travis, which grants access only to a single repo (this one). 

I actually have the ability to add a deploy key to this repo, but in good faith, I'm instead going to post it here and let someone else add it. 

Go to https://github.com/conda/conda-docs/settings/keys
and add the following as a new key:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDC4uH4uB8E0iq4C3wWnbU6i/FW6lKgj+G1MPzdiZuz7xHp7HRngR7X0WvnFH+D/LvZ/TutvLCdbYUmrB8DzXfOOYs0j52sbhgvDyzo0IdrS+XkoWWePhLkUF+zMdAHgoDeFXjp7vxD4gXP/5X9oXHv/bhP5Pw2GkUPGfrJCIeysJJOO6O6qA9YlWvg/i7AZPXim0K8XqD4lKC1LpfMviVH1h9Wy+A03N+UOemlT13WOdnK7IHdtXzcPQO7aWTfPdnx3Dc1JCRV0+uwKdE1QKIHMdYm2RFuvK/hn1mqGDpL2qSAdMFGeHdADYCZ1VlHAcw16vRF5zK/UotWH+q6YM0m9rd47zP4KSvgG7fm41c5hjE6jUarr47I6ZyVN6CIlpSCWlsdwxcOFY8V5Rz1sht+vR92PXOvo3mqRtG1NbiCs8xNWV8agrHueLY2iV9jiNbCvqTsepY+EsVUwmIgNXUSV0DREBdyTNNLoQY0zbl1PviP+APwzbjKBaAKPXN4degSlS+51vB7liZ4Y/OBjm3VZ50eXG/RrkPbvT0F5DYCc7q5xbwuKHpobbsfuq2FK3xe4f+yNuvHatcymDLIwZCKxt25C5iGcMhYgejrm1mh7RBpGZsbmaYqjSXU+s4fvPncjmgHVmkpA1WpxaDC4Fy1I6oriKic5yMAA+PW+2APHw== doctr deploy key for conda/conda-docs
```

Be sure to allow write access for the key.

Unfortunately, due to the nature of doctr, it cannot run on pull requests from forks (for security purposes), and does not run unless on master (this can be disabled with `--no-require-master`). Hence, we won't be able to see if this actually works until it is merged. So when you do merge it, be ready on the revert button in case it breaks. Once it's merged and I've confirmed that it works, I will delete the personal access from my account. 

For reference, the encrypted deploy key in this repo was generated with `doctr configure`. If you ever need to revoke the key (from https://github.com/conda/conda-docs/settings/keys) and regenerate it, use that command.

### CODE REVIEW

**Comment by asmeurer** [comment]
So this is a problem. The continuum-sphinx-theme was never built for Python 3.5, but doctr requires Python >= 3.5. 

The theme was built by me, and the recipe for it is buried in some internal repo. Someone will need to find it and build it (to make it easier for now I can copy it to my repo once it is built)

**Comment by asmeurer** [comment]
Another option would just be to use sphinx_rtd_theme (I think it's the same, except for some color and font differences). I would actually recommend that, until someone can develop a real theme for you guys (the continuum-sphinx-theme I built was super hacked together).

**Comment by asmeurer** [comment]
And if you just want to change some colors in the css it's easier to just put a custom css in the _static directory.

**Comment by asmeurer** [comment]
[Demo of what this looks like](https://asmeurer.github.io/conda-docs-test/docs/)

**Comment by asmeurer** [comment]
So the fonts and colors are different, but on the plus side, the sidebar actually expands to subsections correctly with sphinx_rtd_theme.

**Comment by electronwill** [comment]
No trouble believing that you don't want admin access to a bunch of random repos you once worked on-- having the minimal admin rights necessary is always a good principle, and I always try to do the same. Cleaning up accounts when employees exit is also a good principle, and as you know Continuum always tries their best but sometimes overlooks a small piece or two. Thank you for talking with us about this, and for collaborating with the current Continuum devs to add the new key and make the switch to the new deployment process.

I think you're right that it would be best to switch to sphinx_rtd_theme for now. I can also create an issue to update continuum-sphinx-theme, or make a new theme, or edit the css files, and talk with our designers to see when they'll be able to work on that.

@kalefranz and @msarahan , can one of you please help with reviewing these changes and getting this running soon?

**Comment by msarahan** [comment]
Is this ready to go @asmeurer ?  It looks fine to me.  I really appreciate your effort on this.  You have gone an extra mile here.

**Comment by asmeurer** [comment]
Yes, it is ready to go. Be sure to double check that it works once it is merged, but I have fixed all the issues I know of, and it works in my test repo. 

> You have gone an extra mile here.

Yeah, I already wrote the tool for other purposes (we're using it in SymPy, and I plan to use it for my personal projects). So I figured you might as well use it here too. Anyway, do let me know at https://github.com/drdoctr/doctr if you have an issues with it, or any other feedback.

**Comment by msarahan** [comment]
OK, let's give it a shot.

**Comment by asmeurer** [comment]
Looks like it worked!

https://travis-ci.org/conda/conda-docs/builds/157984436
http://conda.pydata.org/docs/

**Comment by msarahan** [comment]
All thanks to you.  I just pushed some buttons.

**Comment by asmeurer** [comment]
I'll leave the heavy lifting on your side to fixing https://github.com/conda/conda-docs/issues/340 (although if you do end up moving any of those to conda-forge feel free to add me as a maintainer).

**Pull request merged**
