### PR TITLE
docs on md5 sums for miniconda packages.

### PR DESCRIPTION
**Pull request by lexual**

### CODE REVIEW

**Comment by asmeurer** [comment]
There aren't actually sha1 sums published. @kerrywatson1 @electronwill what is the point of having that there? I think we should just have the md5 sum command.

**Comment by kerrywatson1** [comment]
We publish SHA256 and MD5 on http://continuum.io/md5, so it's misleading to
label the link as SHA1 when there are no SHA1's on the linked page.

**Comment by asmeurer** [comment]
Oh I didn't see that the Anaconda page is separate. This as it is now is fine.

**Comment by asmeurer** [comment]
I think we need to keep some kind of "replace <path_to_download_package> with the path to the downloaded package" note to conform to the style guide.

**Comment by electronwill** [comment]
I incorporated these changes and some additional improvements in https://github.com/conda/conda-docs/pull/204 . I believe this pull request may now be closed.

Lexual, thank you very much for offering these corrections to our checksum instructions!

**Pull request closed without merging**
