### PR TITLE
change "conda kapsel" to "conda-kapsel"

### PR DESCRIPTION
**Pull request by electronwill**
change "conda kapsel" to "conda-kapsel"

### CODE REVIEW

**Comment by electronwill** [comment]
If I understand @havocp 's comments from today's Integrated Platform deployment meeting correctly, "conda-kapsel" works in all current and future versions of our software, and "conda kapsel" doesn't. @havocp is that correct?

Also cc @kalefranz .

**Comment by havocp** [comment]
It looks like conda 4.3 no longer chains "conda kapsel" to "conda-kapsel", correct. The version with hyphen should work always.

**Comment by electronwill** [comment]
Thank you!

**Comment by kalefranz** [comment]
I don't think that was intentional.  We did remove some code that was really slowing down process init because of way too much searching.

I don't see where we actually forwarded commands on though in 4.2.x.
https://github.com/conda/conda/blob/4.2.x/conda/cli/main.py

@havocp Do you know of an easy (but still performant) solution here?

**Pull request merged**
