### PR TITLE
add conda to PATH after silent install

### PR DESCRIPTION
**Pull request by electronwill**
add conda to PATH after silent install

### CODE REVIEW

**Comment by mingwandroid** [comment]
It's not my call but I think it would be better if we avoided recommending people to change their PATH variable because it's not sympathetic to other software and it leads people to avoid using proper environment activation (where packages can do arbitrary things when their environment is activated).

I'd at least like a big warning about this. On Windows, for example, people should use the `Anaconda Prompt` which does the right thing and it'd be nice if we had a good equivalent on the other platforms and could instead only ever recommend that approach.

**Comment by electronwill** [comment]
What do you think of this new draft?

I agree that it would be best to have some equivalent to the Windows ``Anaconda Prompt`` so that the PATH is set and the activation scripts are run when the terminal session begins, and the user doesn't have to run ``activate`` or ``source activate`` manually.

**Comment by electronwill** [comment]
Oh, that is a good point. I don't think it affects this PR but it will surely come up sometime.

**Comment by electronwill** [comment]
No wait, that's incorrect-- fixing now

**Comment by electronwill** [comment]
OK, let me know if this needs further changes, and if not I will merge when CI passes.

**Comment by mingwandroid** [comment]
Did you mean to swap between using `$HOME` and `/home/tester`?

**Comment by electronwill** [comment]
Didn't notice it, but it's probably better to use $HOME throughout. That will work in a .bashrc file, right?

**Comment by mingwandroid** [comment]
Yeah, it'll be fine.

**Comment by electronwill** [comment]
Planning to merge this today if no one disagrees.

**Comment by electronwill** [comment]
Deployed and checked at http://conda.pydata.org/docs/help/silent.html .

**Pull request merged**
