### PR TITLE
Update build conda packages docs

### PR DESCRIPTION
**Pull request by saraneem**
Add skeleton files

### CODE REVIEW

**Comment by saraneem** [comment]
@electronwill Can you please review.thanks.

**Comment by electronwill** [comment]
Did your testing find that meta.yaml was created and bld.bat and build.sh were not created?

**Comment by saraneem** [comment]
Yes, only meta.yaml is created.

**Comment by electronwill** [comment]
I'm very glad you tested! Maybe this is a recent change in conda-build. Anyway, if this passes CI it should be ready to merge.

**Pull request merged**
