### PR TITLE
added shell command item

### PR DESCRIPTION
**Pull request by kerrywatson1**

### CODE REVIEW

**Comment by asmeurer** [comment]
@kerrywatson1 I sent you a better worded version on Flowdock.

**Comment by asmeurer** [comment]
Should we rewrite this to not be in third person?

**Comment by asmeurer** [comment]
Good, except it's the shell that searches paths, not the "shell script".

**Comment by kerrywatson1** [comment]
@asmeurer the whole page needs to be updated for adherence to the standards doc -- that is scheduled for the next few days. Please merge this addition. Thanks!

**Comment by kerrywatson1** [comment]
@asmeurer script is removed. Please merge.

**Pull request merged**
