### PR TITLE
Add a warning about mixing noarch and preprocessor selectors

### PR DESCRIPTION
**Pull request by nicoddemus**
Fix conda/conda-build#1024

### CODE REVIEW

**Comment by msarahan** [comment]
Thanks!

**Comment by msarahan** [comment]
To be clear, I'd like it if noarch did support selectors, but that's a bigger job involving both conda and conda build. Conda build needs to record deps for all known platforms. Conda needs to select from those, and also have a default for new unknown platforms. We don't want noarch to actually mean "somearch" with poor definition of what"some" means.

**Comment by nicoddemus** [comment]
>  I'd like it if noarch did support selectors, but that's a bigger job involving both conda and conda build. Conda build needs to record deps for all known platforms. Conda needs to select from those, and also have a default for new unknown platforms. We don't want noarch to actually mean "somearch" with poor definition of what"some" means.

Fully agree with you. My PR was just meant to make this goal explicit.

**Comment by nicoddemus** [comment]
Err now that I revisit it, just to me clear that @msarahan you do an amazing job, and my PR was meant only to help others spend wasting time on this.

**Comment by msarahan** [comment]
Thanks, I really appreciate your efforts also.

**Pull request merged**
