### PR TITLE
hard-code conda-build commands

### PR DESCRIPTION
**Pull request by kalefranz**
follow-on to https://github.com/conda/conda-docs/pull/390

Let's see if this fixes things.  These commands don't change very often.  I think this is an acceptable solution.

If this fixes things though, @msarahan should review the list of commands.

### CODE REVIEW

**Comment by kalefranz** [comment]
We can also remove a lot of unused code here (the `external_commands()` function) if this works.

**Comment by msarahan** [comment]
hooray for docs builds again!

**Comment by electronwill** [comment]
hooray!

**Comment by asmeurer** [comment]
It would actually be useful to have a `conda --help-subcommands` that gave the old `conda --help` output. I was trying to figure out what conda commands I had installed the other day.

**Pull request merged**
