### PR TITLE
edits per meeting last week

### PR DESCRIPTION
**Pull request by kerrywatson1**
@asmeurer please merge. @electronwill

### CODE REVIEW

**Comment by asmeurer** [comment]
Did you want to use the sidebar and note directives in Sphinx for the notes and tips?

**Comment by kerrywatson1** [comment]
@asmeurer no need to add new formatting -- this is a content update only, the marketing guys are going to do a style overhaul later.

**Comment by kerrywatson1** [comment]
@asmeurer please merge. @electronwill

**Comment by kerrywatson1** [comment]
@asmeurer will you please merge this? It is ready to go.

**Pull request merged**
