### PR TITLE
Rearrange build section per Kerry's google doc

### PR DESCRIPTION
**Pull request by electronwill**
Rearranges build section, and removes some minor sections such as
'Post-build version' which were already covered elsewhere.

### CODE REVIEW

**Comment by electronwill** [comment]
@asmeurer @kerrywatson1 Apologies for the large pull request; it's another rearrangement.

In this PR we are (1) moving environment-vars.rst, build-scripts.rst, and meta-yaml.rst out from recipe.rst to their own files, (2) putting Kerry's overview text into recipe.rst, (3) making meta-yaml.rst text with bits of code instead of a huge block of code with comments, (4) making a few tiny corrections in various files, such as removing 'Post-build version' or fixing capitalization, and (5) putting all the files in the right places.

I'm also planning to modify the 'Features' section of meta-yaml.rst, but that can be cleanly separated out into another PR, so I'll do that.

Please let me know if you have any questions, comments, or corrections, and merge when able.

**Comment by asmeurer** [comment]
So should I review this now or is there more work coming?

**Comment by electronwill** [comment]
It's ready now.

**Comment by asmeurer** [comment]
I feel like the recipe page should have a more prominent link to the meta-yaml page, especially since build.html will start redirecting to it.

**Comment by asmeurer** [comment]
This is unrelated to this pull request, but are there plans to replace "NOTE" and "TIP" with Sphinx note and sidebar directives?

**Comment by asmeurer** [comment]
Wasn't there supposed to be a link or inline of an example meta.yaml at the top of the meta-yaml page?

**Comment by kerrywatson1** [comment]
While we use the current Sphinx template, we are not going to use the
Sphinx note and sidebar directives because they are huge and consume the
page -- they become the main focus rather than an aside.

Once we switch to a new template, if necessary, we can do a global change
to the new style.

**Comment by kerrywatson1** [comment]
I remember discussing this, but it looks as if we did not modify the page
text during our working session. This would be very valuable to new users,
so if you can whip up a minimal meta.yaml we can link it into the page text
and make a new PR.

Kerry

**Comment by asmeurer** [comment]
Can we reuse one of the ones from the build tutorials? I think having a very simple example at the top of the meta-yaml page would help a lot.

**Comment by asmeurer** [comment]
I just noticed the meta.yaml in [this page](http://conda.pydata.org/docs/build_tutorials/pkgs2.html) is broken. It seems to be somehow combined from pyfaker and pyinstrument. 

Once that is fixed, though, we should just use it. I think you can extract it into a file and import it to both documents to avoid duplication.

**Comment by asmeurer** [comment]
I think literalinclude from http://sphinx-doc.org/markup/code.html is what you want. I also noticed from that page that you can add captions to code blocks, which is pretty neat.

**Comment by electronwill** [comment]
All sounds like a good approach to me. I started to go look at the tutorials for a good example meta.yaml file and found that same one, but you posted the followup before I got to post here about it. I'll read the http://sphinx-doc.org/markup/code.html page.

**Comment by kerrywatson1** [comment]
@Aaron, so we don't keep increasing the complexity of this already complex
PR, I would like to add the link to an example meta.yaml as a separate
request.

If there are no other issues please merge, and we will immediately do the
meta.yaml as a new, small request.

Kerry

**Comment by asmeurer** [comment]
OK. There's also [this comment](https://github.com/conda/conda-docs/pull/120#issuecomment-114981793).

**Comment by electronwill** [comment]
Yeah, I'll follow up with a PR to add the meta.yaml example with literalinclude, and then another to link from 'recipe' to 'meta-yaml'.

**Pull request merged**
