### PR TITLE
Add 'get involved' section

### PR DESCRIPTION
**Pull request by electronwill**
Add the 'get involved' section, including mailing list, github recipe
repository, and bug report info.

### CODE REVIEW

**Comment by electronwill** [comment]
Ready to go. @asmeurer @kerrywatson1

**Comment by asmeurer** [comment]
I wonder if we should just put these all one one page.

**Comment by kerrywatson1** [comment]
Yes, but with nav links to them.

**Comment by electronwill** [comment]
I must not have understood what you meant when you told me about nav links and bold headers earlier, Kerry. Is it correct to say that you want 'Get Involved' to be done like 'Installation' and not like 'Get more help'?

http://conda.pydata.org/docs/installation.html

http://conda.pydata.org/docs/get-more-help.html

**Comment by kerrywatson1** [comment]
Will, you can ask Susan, and if she is unclear we'll have to look at it
tomorrow. I don't have it in front of me to check. Susan is terrific at
navigation and usability and she can overrule me on that.

**Comment by kerrywatson1** [comment]
We decided that putting them on one page with anchor links was fine - since anchor links still show up in the nav.

We wanted the options to show in nav - but they will.

-Susan

**Comment by electronwill** [comment]
OK, great! Susan just said the same, so I've merged all the 'Get Involved' info into one page, with the links showing up correctly on the side.

**Comment by electronwill** [comment]
OK, Kerry has approved this version, and this PR is ready to merge.

**Pull request merged**
