### PR TITLE
more info on environment variable scripts

### PR DESCRIPTION
**Pull request by electronwill**
more info on environment variable scripts

### CODE REVIEW

**Comment by electronwill** [comment]
per discussion in https://github.com/conda/conda-docs/pull/301 . fyi @msarahan .

**Comment by stevenengler** [comment]
Thanks @electronwill, that's formatted much better.

**Comment by electronwill** [comment]
Happy to. Thank you for providing the information!

**Comment by stevenengler** [comment]
Very minor note @electronwill, on Windows it is just `activate analytics` and `deactivate` rather than `source activate analytics` and `source deactivate`. I don't know if it's possible to commit to an already-merged PR or not, so just thought I'd let you know.

**Comment by electronwill** [comment]
Oh rats... I should have caught that. Thank you for telling me.

**Comment by stevenengler** [comment]
I missed it the first time too, so no problem!

**Pull request merged**
