### PR TITLE
Update download.rst

### PR DESCRIPTION
**Pull request by jeremytanner**
Change 100 GB to 1.2

### CODE REVIEW

**Comment by electronwill** [comment]
I believe this is also covered in https://github.com/conda/conda-docs/pull/167 -- we need to clear the pull request backlog in this repo

**Comment by ilanschnell** [comment]
Why does ti say `20 minutes to an hour to install`?  It does not take such a long time to install.

**Comment by electronwill** [comment]
I believe the best thing to do is merge PR #167  and close this one; 167 standardizes all the installation requirements, including saying that it takes "less than 20 minutes".

**Comment by ilanschnell** [comment]
Once Anaconda is downloaded, it should only take a few minutes to install it.  More precisely, running the actual installer only takes just a few minutes.  "less than 20 minutes" makes it should like it's a long process (which it is not).

**Comment by electronwill** [comment]
ok, I'll edit PR #167 and post here once that's done

**Comment by electronwill** [comment]
PR #167 should be ready to go

**Comment by electronwill** [comment]
Since PR #167 was merged in and solved all this, this pull request #169 is ready to be closed.

**Pull request closed without merging**
