### PR TITLE
Remove git_rev from pkgs2 tutorial

### PR DESCRIPTION
**Pull request by electronwill**
In response to bug report and correction from Elizabeth Albin, remove
git_rev from meta.yaml and other code in pkgs2 build tutorial.

### CODE REVIEW

**Comment by electronwill** [comment]
@asmeurer Elizabeth reports that taking the tutorial causes an error in the conda build where git says the revision is not present, and after removing the git_rev lines the conda build works correctly. Does it make sense that users would be getting this error from the current instructions? Is removing these lines the best fix, or would changing the value or some other fix be better?

**Comment by asmeurer** [comment]
-1. This sounds like a bug, which should be fixed in the code, not the documentation.

**Comment by lizalbin** [comment]
Shall I report it as a conda bug?

**Comment by asmeurer** [comment]
A [conda-build](https://github.com/conda/conda-build) bug, yes.

**Pull request closed without merging**
