### PR TITLE
correct section on subpackage requirements

### PR DESCRIPTION
**Pull request by msarahan**

### CODE REVIEW

**Comment by msarahan** [comment]
@cio-docs please review when convenient.  This is confusing users, as evidenced by https://github.com/conda/conda-build/issues/2229

**Comment by kerrywatson1** [comment]
Will, do you think this might be easier to understand as a list?

**Comment by msarahan** [comment]
I think it's accurate.  I have no opinion on whether it's clearer.  Need third party!

**Comment by electronwill** [comment]
Thank you! I went ahead and updated the text to this version. I think this is ready to merge, if the clarity is OK. @kerrywatson1 what do you think?

**Comment by kerrywatson1** [comment]
Ready if you are.

**Comment by electronwill** [comment]
The option with no build or run section isn't really an example of anything discussed before that, so I rephrased it a little.

**Comment by kerrywatson1** [comment]
LGTM.

**Pull request merged**
